### ISSUE TITLE
NPE in GUI

### ISSUE THREAD

**Issue by VADemon** [EmotionalLove/ReMinecraft#22]
https://github.com/EmotionalLove/ReMinecraft/blob/master/src/main/java/com/sasha/reminecraft/javafx/ReMinecraftGui.java#L45

Running latest release available on Github. Java: "1.8.0_201"

```
Starting RE:Minecraft 2.0.5 for Minecraft 1.12.2
Exception in Application start method
Exception in thread "Thread-1" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.sasha.reminecraft.javafx.ReMinecraftGui.start(ReMinecraftGui.java:45)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        ... 1 more
```

**Comment by EvilSourcerer** [comment]
run it with no gui (`-nogui`)

**Comment by EmotionalLove** [comment]
This is a known issue and the GUI is probably going to be remade in Swing. If anyone wants like like highkey do this for me and pr it that would be hella appreciated because I might not have time.

**Comment by EmotionalLove** [comment]
you all just don't stop harassing me, hm? https://i.imgur.com/T3uROpy.png
k
